import { VideoGame } from './interfaces';

export const VIDEO_GAMES: VideoGame[] = [
  {
    title: 'Valorant',
    company: 'Riot Games',
    description: "Blend your style and experience on a global, competitive stage. You have 13 rounds to attack and defend your side using sharp gunplay and tactical abilities. And, with one life per-round, you'll need to think faster than your opponent if you want to survive. Take on foes across Competitive and Unranked modes as well as Deathmatch and Spike Rush.",
    image_url: 'valorant',
    video_url: 'https://www.youtube.com/embed/e_E9W2vsRbQ',
    tags: ['Shooter', 'Action', 'Teams'],
    release: 'Jun 6, 2020',
    score: 4.9,
    platform: ['windows'],
    available: true,
    offer: false,
    price: 0,
  },
  {
    title: 'Watch Dogs: Legion',
    company: 'Ubisoft',
    description: "In Watch Dogs: Legion your mission is to form a resistance to save London from debacle in the near future.",
    image_url: 'wdl',
    video_url: 'https://www.youtube.com/embed/F11svbrAaA0',
    tags: ['Action', 'Multiplayer', 'Open world'],
    release: 'Oct 29, 2020',
    score: 4.8,
    platform: ['windows', 'ps4'],
    available: true,
    offer: false,
    price: 129,
  },
  {
    title: 'Grand Theft Auto V',
    company: 'Rockstar Games',
    description: "The Grand Theft Auto V: Premium Edition includes the complete GTAV story, Grand Theft Auto Online and all existing gameplay upgrades and content. You’ll also get the Criminal Enterprise Starter Pack, the fastest way to jumpstart your criminal empire in GTA Online.",
    image_url: 'gtav',
    video_url: 'https://www.youtube.com/embed/QkkoHAzjnUs',
    tags: ['Action', 'Adventure'],
    release: 'Sep 17, 2013',
    score: 4.8,
    platform: ['windows', 'ps4', 'xbox'],
    available: true,
    offer: true,
    deduction: 25,
    price: 100,
  },
]
